# 使用inspect模块生成的高级存根文件
# 包含参数名和类型提示

from typing import Any, Optional, List, Dict, Union, Callable

class WeChatPYApi:
    """基于PC微信的Python-API"""

    def __init__(*args, **kwargs) -> None:
        ...

    def add_friend_by_chat_room(self, chat_room_id, wx_id, msg) -> Any:
        ...

    def add_friend_by_net(self, v3, v4, msg) -> Any:
        ...

    def agree_friend(self, msg_data) -> Any:
        ...

    def agree_friend_invite_join_chat_room(self, msg_data) -> Any:
        ...

    def alter_chat_room_name(self, to_chat_room, name) -> Any:
        ...

    def alter_friend_desc(self, to_wx, desc) -> Any:
        ...

    def alter_friend_remark(self, to_wx, remark) -> Any:
        ...

    def alter_my_name_in_chat_room(self, to_chat_room, name) -> Any:
        ...

    def batch_query_member_nick_name(self, to_chat_room, wx_id_list) -> Any:
        ...

    def cdn_download_file(self, file_id, aes_key, save_path) -> Any:
        ...

    def cdn_download_img(self, img_type, file_id, aes_key, save_path) -> Any:
        ...

    def cdn_download_video(self, file_id, aes_key, save_path) -> Any:
        ...

    def collection(self, msg_data) -> Any:
        ...

    def comment_moments(self, moments_id, content) -> Any:
        ...

    def create_chat_room(self, wx_id_list) -> Any:
        ...

    def del_comment_moments(self, moments_id, comment_id) -> Any:
        ...

    def delete_chat_room_member(self, to_chat_room, to_wx_list) -> Any:
        ...

    def delete_friend(self, to_wx) -> Any:
        ...

    def exit_chat_room(self, to_chat_room) -> Any:
        ...

    def follow_mp(self, mp_id) -> Any:
        ...

    def get_access_url(self, url) -> Any:
        ...

    def get_chat_room_members(self, to_chat_room) -> Any:
        ...

    def get_cur_window_info(self) -> Any:
        ...

    def get_cur_wx_pid(self) -> Any:
        ...

    def get_login_state(self) -> Any:
        ...

    def get_moments(self, last_id = None) -> Any:
        ...

    def get_moments_by_friend(self, wx_id, last_id = None) -> Any:
        ...

    def get_self_info(self) -> Any:
        ...

    def get_small_app_code(self, app_id) -> Any:
        ...

    def hide_wx_windows(self) -> Any:
        ...

    def invite_friend_enter_chat_room(self, to_chat_room, to_wx_list) -> Any:
        ...

    def like_moments(self, moments_id, state) -> Any:
        ...

    def logout(self) -> Any:
        ...

    def mask_msg_switch(self, to_id, switch) -> Any:
        ...

    def moments_upload_img(self, path) -> Any:
        ...

    def pull_list(self, pull_type) -> Any:
        ...

    def qr_code_join_chat_room(self, url) -> Any:
        ...

    def query_friend_info(self, to_wx) -> Any:
        ...

    def query_friend_info_by_net(self, to_wx) -> Any:
        ...

    def query_wx_info_by_net(self, key) -> Any:
        ...

    def refund(self, msg_data) -> Any:
        ...

    def save_to_addr_book(self, to_chat_room, switch) -> Any:
        ...

    def save_voice_switch(self, save_dir_path, switch) -> Any:
        ...

    def send_card_link(self, to_wx, title, desc, target_url, img_url) -> Any:
        ...

    def send_card_link_moments(self, text, title, desc, target_url, thumb_url, is_private = ...) -> Any:
        ...

    def send_file(self, to_wx, path) -> Any:
        ...

    def send_friend_card(self, to_wx, friend_wx, friend_name) -> Any:
        ...

    def send_gif(self, to_wx, path) -> Any:
        ...

    def send_img(self, to_wx, path) -> Any:
        ...

    def send_img_text_moments(self, text, img_url_list = None, is_private = ...) -> Any:
        ...

    def send_location(self, to_wx, lon, lat, address, detail_address) -> Any:
        ...

    def send_mp_card(self, to_wx, mp_id, mp_name) -> Any:
        ...

    def send_notice(self, to_chat_room, content) -> Any:
        ...

    def send_or_forward_moments(self, xml_content, is_private = ...) -> Any:
        ...

    def send_text(self, to_wx, msg) -> Any:
        ...

    def send_text_and_at_all(self, to_chat_room, msg) -> Any:
        ...

    def send_text_and_at_member(self, to_chat_room, to_wx_list, msg) -> Any:
        ...

    def send_voice(self, to_wx, path, voice_time) -> Any:
        ...

    def send_xml(self, to_wx, xml_str) -> Any:
        ...

    def show_wx_windows(self) -> Any:
        ...

    def start_wx(self, path = None) -> Any:
        ...

    def top_chat_switch(self, to_id, switch) -> Any:
        ...

    def un_follow_mp(self, mp_id) -> Any:
        ...
